### ISSUE TITLE
Release plan for 2.0 version? Current Maven (RC4) artifact's stableness? 

### ISSUE THREAD

**Issue by gilnoh** [inoio/solrs#24]
(I am sorry that I am writing a question to the issue tracker --- I couldn't find the user board or user mailing list. Feel free to delete this issue and forward me to proper place for asking release related question.) 

This is a wonderful library that fills our need. I've been testing SolrS to replace SolrJ synchronous queries on our backend servers, and it seems to work well. 

Here's my questions. 
- The documentation says "use RC3", but RC3 has some limitations like missing methods (e.g. deletions, etc), and missing capabilities (e.g. query method as POST), compared to the source code of master branch. 
- On Maven central, there is RC4 artifact, which seems to be in line with current master branch. I guess I should use RC4. 
- We are about to use RC4 on a productive environment --- will there be any pitfall I should be careful, or to worry about? :-) 

Thanks again for this great library.

Gil 
OMQ GmbH

**Comment by magro** [comment]
Hi @gilnoh, no worries, great issue! If you're looking for a place to ask questions you can use gitter: https://gitter.im/inoio/solrs

That the readme mentions RC3 is outdated as you noticed.

We're running the RCs in production for several months now, so I'd call it stable.

A thing that I wanted to add before releasing 2.0 was #15, because this will break binary compatibility. Unfortunately until now I didn't find the time to do this (also because it's only an api issue, nothing functional/critical). 
Because nobody so far asked for it we could also leave it as it is and make the release.

But, as already said, you can also already go with the current RC4.

**Comment by gilnoh** [comment]
Thanks for the reply. :-)
