### ISSUE TITLE
scala-xml version conflict

### ISSUE THREAD

**Issue by magro** [inoio/solrs#87]
This was raised via gitter, https://gitter.im/inoio/solrs?at=61d5ad25526fb77b3164391f:

> I am using solrs with some of frameworks (lagom/akka/play), but after newest PR i have binary compatibility confict because of scala xml (framework use 1.x.x which is not binary compatible with new 2.x.x). I know that i have small chances to ask for frameworks to do a update to newest version of this xml library ( i know that lagom now is mainly in support mode like security fixes).
> 
> I have a question if it is posible to have solrs release with downgraded scala-xml?

The issue here shall track this compatibility issue. One option to deal with this issue should be to downgrade/fix scala-xml to the version need by a framework like lagom.

**Comment by magro** [comment]
Submitted https://github.com/lagom/lagom/pull/3330 for updating scala-xml in lagom - let's see what happens.

**Comment by Randerspl** [comment]
For clarification:
I'm using newest lagom (currently for this time 1.6.7) and sbt 1.6.x and got this stack trace:
![image](https://user-images.githubusercontent.com/9450923/148352464-0e22f904-0cfa-4482-86a7-48d2a22a4355.png)
This is a little bit funny, because before PR #84 lagom updated in 1.6.7 scala-java8-compat ( to 1.x.x ) and i had conflict with this library, but after PR library changed to scala-xml and conflict occurred again but in reversed direction (newest in solrs :P).

I'm not using schema manipulation in solr (just insert/selects) and it seems initially to work when i just changed evictionErrorLevel to warn, but i found in [scala-xml 2.0.0-M1 changelog](https://github.com/scala/scala-xml/blob/v2.0.0-M1/CHANGELOG.md) that new version is not compatible binary with  1.2.x.

**Comment by magro** [comment]
Closing because lagom/lagom#3330 respectively lagom/lagom#3333 got merged.
